"""add_custom_data_and_history_tables

Revision ID: 2124bc786e21
Revises: '3d3360227021'
Create Date: 2025-06-01 16:36:35.827554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2124bc786e21'
down_revision: Union[str, None] = '3d3360227021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_item_type', sa.String(), nullable=False),
    sa.Column('source_item_id', sa.String(), nullable=False),
    sa.Column('target_item_type', sa.String(), nullable=False),
    sa.Column('target_item_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_links_id'), 'context_links', ['id'], unique=False)
    op.create_index(op.f('ix_context_links_relationship_type'), 'context_links', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_context_links_source_item_id'), 'context_links', ['source_item_id'], unique=False)
    op.create_index(op.f('ix_context_links_source_item_type'), 'context_links', ['source_item_type'], unique=False)
    op.create_index(op.f('ix_context_links_target_item_id'), 'context_links', ['target_item_id'], unique=False)
    op.create_index(op.f('ix_context_links_target_item_type'), 'context_links', ['target_item_type'], unique=False)
    op.create_table('custom_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'key', name='uq_custom_data_category_key')
    )
    op.create_index(op.f('ix_custom_data_category'), 'custom_data', ['category'], unique=False)
    op.create_index(op.f('ix_custom_data_id'), 'custom_data', ['id'], unique=False)
    op.create_index(op.f('ix_custom_data_key'), 'custom_data', ['key'], unique=False)
    op.create_table('progress_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['progress_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_entries_id'), 'progress_entries', ['id'], unique=False)
    op.create_table('system_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_system_patterns_id'), 'system_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_active_context_id'), 'active_context', ['id'], unique=False)
    op.create_index(op.f('ix_active_context_history_id'), 'active_context_history', ['id'], unique=False)
    op.drop_constraint(None, 'active_context_history', type_='foreignkey')
    op.create_foreign_key(None, 'active_context_history', 'active_context', ['active_context_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.create_index(op.f('ix_product_context_id'), 'product_context', ['id'], unique=False)
    op.create_index(op.f('ix_product_context_history_id'), 'product_context_history', ['id'], unique=False)
    op.drop_constraint(None, 'product_context_history', type_='foreignkey')
    op.create_foreign_key(None, 'product_context_history', 'product_context', ['product_context_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_context_history', type_='foreignkey')
    op.create_foreign_key(None, 'product_context_history', 'product_context', ['product_context_id'], ['id'])
    op.drop_index(op.f('ix_product_context_history_id'), table_name='product_context_history')
    op.drop_index(op.f('ix_product_context_id'), table_name='product_context')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_constraint(None, 'active_context_history', type_='foreignkey')
    op.create_foreign_key(None, 'active_context_history', 'active_context', ['active_context_id'], ['id'])
    op.drop_index(op.f('ix_active_context_history_id'), table_name='active_context_history')
    op.drop_index(op.f('ix_active_context_id'), table_name='active_context')
    op.drop_index(op.f('ix_system_patterns_id'), table_name='system_patterns')
    op.drop_table('system_patterns')
    op.drop_index(op.f('ix_progress_entries_id'), table_name='progress_entries')
    op.drop_table('progress_entries')
    op.drop_index(op.f('ix_custom_data_key'), table_name='custom_data')
    op.drop_index(op.f('ix_custom_data_id'), table_name='custom_data')
    op.drop_index(op.f('ix_custom_data_category'), table_name='custom_data')
    op.drop_table('custom_data')
    op.drop_index(op.f('ix_context_links_target_item_type'), table_name='context_links')
    op.drop_index(op.f('ix_context_links_target_item_id'), table_name='context_links')
    op.drop_index(op.f('ix_context_links_source_item_type'), table_name='context_links')
    op.drop_index(op.f('ix_context_links_source_item_id'), table_name='context_links')
    op.drop_index(op.f('ix_context_links_relationship_type'), table_name='context_links')
    op.drop_index(op.f('ix_context_links_id'), table_name='context_links')
    op.drop_table('context_links')
    # ### end Alembic commands ###