"""create_initial_conport_tables_v2

Revision ID: 3d3360227021
Revises: None
Create Date: 2025-06-01 14:26:07.936055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3360227021'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Основные таблицы
    op.create_table('product_context',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content', sa.JSON(), nullable=False, server_default='{}'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('active_context',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content', sa.JSON(), nullable=False, server_default='{}'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('rationale', sa.Text(), nullable=True),
        sa.Column('implementation_details', sa.Text(), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Таблицы истории
    op.create_table('product_context_history',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('product_context_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('content', sa.JSON(), nullable=False),
        sa.Column('change_source', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['product_context_id'], ['product_context.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('active_context_history',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('active_context_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('content', sa.JSON(), nullable=False),
        sa.Column('change_source', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['active_context_id'], ['active_context.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###

    # Вставка начальных данных в основные таблицы
    # (SQLAlchemy ORM модели ProductContextORM и ActiveContextORM имеют default=1 для id
    # и default={} для content, но для явной инициализации через Alembic это надежнее)
    product_context_table_ref = sa.table('product_context',
                                       sa.column('id', sa.Integer),
                                       sa.column('content', sa.JSON)
                                      )
    active_context_table_ref = sa.table('active_context',
                                      sa.column('id', sa.Integer),
                                      sa.column('content', sa.JSON)
                                     )
    op.bulk_insert(product_context_table_ref, [{'id': 1, 'content': '{}'}])
    op.bulk_insert(active_context_table_ref, [{'id': 1, 'content': '{}'}])

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_context_history')
    op.drop_table('product_context_history')
    op.drop_table('decisions')
    op.drop_table('active_context')
    op.drop_table('product_context')
    # ### end Alembic commands ###